# Generated by Django 3.0.2 on 2021-06-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(default='https://www.amazon.in', max_length=1000),
        ),
    ]
