# Generated by Django 3.0.2 on 2021-06-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0002_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(),
        ),
    ]
